import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

// Styles for the analysis report
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    borderBottom: '2 solid #4F46E5',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 12,
    color: '#6B7280',
  },
  section: {
    marginTop: 20,
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#4F46E5',
    marginBottom: 10,
    borderBottom: '1 solid #E5E7EB',
    paddingBottom: 5,
  },
  subsectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#374151',
    marginTop: 10,
    marginBottom: 5,
  },
  scoreBox: {
    backgroundColor: '#F3F4F6',
    padding: 15,
    borderRadius: 5,
    marginBottom: 15,
  },
  scoreRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 5,
  },
  scoreLabel: {
    fontSize: 11,
    color: '#6B7280',
  },
  scoreValue: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1F2937',
  },
  bullet: {
    flexDirection: 'row',
    marginBottom: 5,
    paddingLeft: 10,
  },
  bulletText: {
    fontSize: 10,
    color: '#374151',
    flex: 1,
  },
  priorityHigh: {
    color: '#DC2626',
    fontWeight: 'bold',
  },
  priorityMedium: {
    color: '#F59E0B',
    fontWeight: 'bold',
  },
  priorityLow: {
    color: '#10B981',
    fontWeight: 'bold',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    color: '#9CA3AF',
    fontSize: 8,
    borderTop: '1 solid #E5E7EB',
    paddingTop: 10,
  },
});

interface AnalysisReportProps {
  quickAnalysis: any;
  sectionAnalysis?: any;
  languageAnalysis?: any;
  careerAnalysis?: any;
  insightsAnalysis?: any;
  resumeData: any;
}

export const AnalysisReportTemplate = ({
  quickAnalysis,
  sectionAnalysis,
  languageAnalysis,
  careerAnalysis,
  insightsAnalysis,
  resumeData,
}: AnalysisReportProps) => (
    <Document>
      {/* Page 1: Overview & Quick Analysis */}
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Resume Analysis Report</Text>
          <Text style={styles.subtitle}>
            {resumeData?.personalInfo?.name || 'Resume Analysis'} • Generated by Draftr
          </Text>
        </View>

        {/* Overall Scores */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>📊 Overall Scores</Text>
          <View style={styles.scoreBox}>
            <View style={styles.scoreRow}>
              <Text style={styles.scoreLabel}>Overall Score</Text>
              <Text style={styles.scoreValue}>{quickAnalysis.scores.overall}/100</Text>
            </View>
            <View style={styles.scoreRow}>
              <Text style={styles.scoreLabel}>ATS Compatibility</Text>
              <Text style={styles.scoreValue}>{quickAnalysis.scores.ats}/100</Text>
            </View>
            <View style={styles.scoreRow}>
              <Text style={styles.scoreLabel}>Clarity</Text>
              <Text style={styles.scoreValue}>{quickAnalysis.scores.clarity}/100</Text>
            </View>
            <View style={styles.scoreRow}>
              <Text style={styles.scoreLabel}>Impact</Text>
              <Text style={styles.scoreValue}>{quickAnalysis.scores.impact}/100</Text>
            </View>
          </View>
        </View>

        {/* Quick Wins */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>⚡ Quick Wins</Text>
          {quickAnalysis.quickWins.map((win: any, idx: number) => (
            <View key={idx} style={styles.bullet}>
              <Text style={[
                styles.bulletText,
                win.priority === 'High' ? styles.priorityHigh :
                win.priority === 'Medium' ? styles.priorityMedium :
                styles.priorityLow
              ]}>
                [{win.priority}] {win.text}
              </Text>
            </View>
          ))}
        </View>

        {/* Key Strengths */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>✓ Key Strengths</Text>
          {quickAnalysis.keyStrengths.map((strength: string, idx: number) => (
            <View key={idx} style={styles.bullet}>
              <Text style={styles.bulletText}>• {strength}</Text>
            </View>
          ))}
        </View>

        {/* Top Issues */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>⚠ Top Issues</Text>
          {quickAnalysis.topIssues.map((issue: string, idx: number) => (
            <View key={idx} style={styles.bullet}>
              <Text style={styles.bulletText}>• {issue}</Text>
            </View>
          ))}
        </View>

        <Text style={styles.footer}>
          Page 1 • Generated by Draftr • draftr.ai
        </Text>
      </Page>

      {/* Page 2: Section Analysis (if available) */}
      {sectionAnalysis && (
        <Page size="A4" style={styles.page}>
          <View style={styles.header}>
            <Text style={styles.title}>Section Analysis</Text>
          </View>

          {sectionAnalysis.sectionAnalysis.slice(0, 3).map((section: any, idx: number) => (
            <View key={idx} style={styles.section}>
              <Text style={styles.subsectionTitle}>{section.name}</Text>
              <Text style={styles.bulletText}>
                Word Count: {section.metrics.word_count} • Readability: {section.metrics.readability_score}/100
              </Text>
              {section.suggestions.slice(0, 2).map((suggestion: any, sIdx: number) => (
                <View key={sIdx} style={styles.bullet}>
                  <Text style={styles.bulletText}>• {suggestion.text}</Text>
                </View>
              ))}
            </View>
          ))}

          <Text style={styles.footer}>
            Page 2 • Generated by Draftr • draftr.ai
          </Text>
        </Page>
      )}

      {/* Page 3: Career Roadmap (if available) */}
      {careerAnalysis && (
        <Page size="A4" style={styles.page}>
          <View style={styles.header}>
            <Text style={styles.title}>Career Roadmap</Text>
          </View>

          {careerAnalysis.careerRoadmap.target_roles.slice(0, 2).map((role: any, idx: number) => (
            <View key={idx} style={styles.section}>
              <Text style={styles.subsectionTitle}>{role.role_name}</Text>
              <Text style={styles.bulletText}>Timeframe: {role.timeframe}</Text>
              <Text style={styles.bulletText}>Skill Match: {role.metrics.skill_match_percentage}%</Text>
              
              <Text style={{ fontSize: 10, fontWeight: 'bold', marginTop: 5 }}>Missing Skills:</Text>
              {role.gaps.missing_skills.slice(0, 3).map((skill: string, sIdx: number) => (
                <View key={sIdx} style={styles.bullet}>
                  <Text style={styles.bulletText}>• {skill}</Text>
                </View>
              ))}
            </View>
          ))}

          <Text style={styles.footer}>
            Page 3 • Generated by Draftr • draftr.ai
          </Text>
        </Page>
      )}
    </Document>
);
